backend:
  name: github
  repo: MuuLinnk/personal-blog
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    label_singular: "文章"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "摘要", name: "description", widget: "text", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "自定义链接", name: "slug", widget: "string", required: false, hint: "留空则自动用标题生成" }
      - { label: "正文", name: "body", widget: "markdown" }
